guest_os="linux_old"
disk_img="vm.qcow2"
# iso="./ubuntu-6.06.1-desktop-amd64.iso"
iso="./ubuntu-8.04.4-desktop-amd64.iso"
disk_size="10G"
boot="legacy"

cpu_cores="4"
ram="3G"
# port_forwards=("33890:3389" )
